--- # Ignore errors example
- hosts: web
  remote_user: user
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute command that does not exist
      action: shell /bin/coco
      ignore_errors: yes
    - name: Do smth useful
      action: shell /bin/ls
